services:
  chronosuite:
    build: .
    container_name: chronodrive
    restart: always
    ports:
      - "3939:3939"
    volumes:
      - ./data:/app/data
    environment:
      API_URLS: "https://atomone-api.allinbits.com,https://atomone-rest.publicnode.com"
      START_BLOCK: "4327701"
      BATCH_SIZE: 50
      # MEMO_PREFIX: "0xTest"
      # RECEIVER: process.env.RECEIVER,
      # SENDER: process.env.SENDER,
      LOG: 'true'
    command: ["pnpm", "start"]