services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: actions
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
  chronosync-postgres:
    build: .
    container_name: chronosync-postgres
    restart: always
    ports:
      - "3939:3939"
    volumes:
      - ./data:/app/data
    environment:
      API_URLS: "https://atomone-api.allinbits.com,https://atomone-rest.publicnode.com"
      START_BLOCK: "4846817"
      BATCH_SIZE: 50
      PG_URI: postgres://username:password@postgres:5432/actions
    depends_on:
      postgres:
        condition: service_healthy
    command: ["pnpm", "start"]